dataset:
  name: "fashionmnist"
  root: "../../data"
  batch_size: 128
  num_workers: 4  
  augment: true

model:
  type: resnet_transfer 
  num_classes: 10
  dropout: 0.5

training:
  epochs: 50 
  learning_rate: 0.001  
  weight_decay: 0.0001
  checkpoint_dir: "../../checkpoints"
  checkpoint_name: "resnet_fmnist_aug.pt"

misc:
  seed: 19
